services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
    command:
      - "start-dev"
    networks:
      - my_network

  terraform:
    build:
      context: ./terraform
      dockerfile: Dockerfile
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - my_network
    entrypoint: /bin/sh
    command: "-c './wait-for-keycloak.sh && terraform -chdir=objects init && terraform -chdir=objects apply -auto-approve'"
    volumes:
      - ./terraform:/app

  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    environment:
      DATABASE_URL: postgres://your_user:your_password@postgres:5432/your_db
    deploy:
      replicas: 3  # Define 3 réplicas de la aplicación
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
